### ISSUE TITLE
discard_config() fails when diff is empty

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-sros#21]
discard_config() fails when the candidate config is the same as the running config. 

I'm using configs in XML format and doing
>\>>> device.close()
\>>> device.open()
\>>> device.load_merge_candidate('./tests/payloads/filter200-swap.xml')
\>>> device.compare_config()
''
\>>> device.discard_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marek/Projects/nokia-napalm-tests/.tox/py3-test/lib/python3.8/site-packages/napalm_sros/sros.py", line 272, in discard_config
    self._unlock_config()
  File "/home/marek/Projects/nokia-napalm-tests/.tox/py3-test/lib/python3.8/site-packages/napalm_sros/sros.py", line 206, in _unlock_config
    self.conn.unlock()
  File "/home/marek/Projects/nokia-napalm-tests/.tox/py3-test/lib/python3.8/site-packages/ncclient/manager.py", line 239, in execute
    return cls(self._session,
  File "/home/marek/Projects/nokia-napalm-tests/.tox/py3-test/lib/python3.8/site-packages/ncclient/operations/lock.py", line 49, in request
    return self._request(node)
  File "/home/marek/Projects/nokia-napalm-tests/.tox/py3-test/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 367, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: 
            MINOR: NETCONF #2052: Current session does not hold the lock

The same happens with `load_replace_candidate`. But if the candidate config differs the `discard_config()` works fine.

**Comment by ashah26** [comment]
Hey, 

I am trying to reproduce this using the following script:
```from napalm import get_network_driver

# import napalm driver and open the connection
driver = get_network_driver("sros")
optional_args = {"port": 830}
# device = driver("127.0.0.1", "vagrant", "vagrant", 60, optional_args)
device = driver("ip-address", "admin", "admin", 60, optional_args)
device.open()

# call load_replace
device.load_replace_candidate(filename="running_config.xml")


# xml diff between candidate and running
print(device.compare_config())

#
device.discard_config()
```
There is no diff between candidate and running. But I am unable to get the error 
Can you take a look and let me know if I am missing something ?

**Comment by JonLundstrom** [comment]
@omron93 - appreciate any input you have on our method to reproduce this issue. Thanks in advance.

**Comment by omron93** [comment]
@ashah26 Sorry for late answer. Please try with the `load_replace_candidate(config=running_config_string)`

**Comment by omron93** [comment]
@ashah26 @JonLundstrom I've tried again and I'm no longer able to reproduce it. Although I haven't made up the traceback :-), now even with the same config it works fine. So it was probably problem on my side, sorry. I guess the issue can be closed.

**Comment by JonLundstrom** [comment]
Thanks @omron93 . We will close this, but if you see it again, please let us know.
